x-environment: &glitchtip-environment
  DATABASE_URL: ${DATABASE_URL}
  REDIS_URL: ${REDIS_URL}
  SECRET_KEY: ${SECRET_KEY}
  PORT: ${GLITCHTIP_PORT}
  EMAIL_URL: ${EMAIL_URL}
  GLITCHTIP_DOMAIN: ${GLITCHTIP_DOMAIN}
  DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
  CELERY_WORKER_AUTOSCALE: "1,3"
  CELERY_WORKER_MAX_TASKS_PER_CHILD: "10000"

x-depends_on: &glitchtip-depends
  - postgres
  - redis

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    restart: unless-stopped
    volumes:
      - glitchtip-pg:/var/lib/postgresql/data

  redis:
    image: redis
    restart: unless-stopped

  web:
    image: glitchtip/glitchtip:v4.0
    depends_on: *glitchtip-depends
    ports:
      - "${GLITCHTIP_PORT}:8000"
    environment: *glitchtip-environment
    restart: unless-stopped
    volumes:
      - glitchtip-uploads:/code/uploads

  worker:
    image: glitchtip/glitchtip:v4.0
    command: ./bin/run-celery-with-beat.sh
    depends_on: *glitchtip-depends
    environment: *glitchtip-environment
    restart: unless-stopped
    volumes:
      - glitchtip-uploads:/code/uploads

  migrate:
    image: glitchtip/glitchtip:v4.0
    depends_on: *glitchtip-depends
    command: "./manage.py migrate"
    environment: *glitchtip-environment

volumes:
  glitchtip-pg:
  glitchtip-uploads:
