blank_issues_enabled: true
contact_links:
  - name: ğŸ“š DocumentaÃ§Ã£o
    url: https://github.com/brunopintobrum/kovoy_app/blob/main/README.md
    about: Consulte a documentaÃ§Ã£o do projeto
  - name: ğŸ’¬ DiscussÃµes
    url: https://github.com/brunopintobrum/kovoy_app/discussions
    about: FaÃ§a perguntas ou inicie discussÃµes sobre o projeto
